Repository robbrad/UKBinCollectionData, pull requests merged in 2023-10, with the labels that each got.

#361 fix: Various council fixes
  poetry.lock
  pyproject.toml
  uk_bin_collection/tests/input.json
  uk_bin_collection/uk_bin_collection/councils/BasingstokeCouncil.py
  uk_bin_collection/uk_bin_collection/councils/BathAndNorthEastSomersetCouncil.py
  uk_bin_collection/uk_bin_collection/councils/BlackburnCouncil.py
  uk_bin_collection/uk_bin_collection/councils/BromleyBoroughCouncil.py
  uk_bin_collection/uk_bin_collection/councils/CrawleyBoroughCouncil.py
  uk_bin_collection/uk_bin_collection/councils/HarrogateBoroughCouncil.py
  uk_bin_collection/uk_bin_collection/councils/MalvernHillsDC.py
  uk_bin_collection/uk_bin_collection/councils/SwaleBoroughCouncil.py
  wiki/Councils.md
Labels: python

#368 fix: Update poetry.lock
  poetry.lock
Labels: bug, dependencies

#369 fix: Update poetry.lock to allow any urllib3 version
  poetry.lock
  pyproject.toml
Labels: bug, dependencies, home assistant custom component

#370 docs: Update council request issue template
  .github/ISSUE_TEMPLATE/COUNCIL_ISSUE.yaml
  .github/ISSUE_TEMPLATE/COUNCIL_REQUEST.yaml
  .github/ISSUE_TEMPLATE/HOME_ASSISTANT_CUSTOM_COMPONENT_ISSUE.yaml
Labels: documentation

#375 StratfordUponAvonCouncil Addition
  uk_bin_collection/tests/council_schemas/StratfordUponAvonCouncil.schema
  uk_bin_collection/tests/features/validate_council_outputs.feature
  uk_bin_collection/tests/input.json
  uk_bin_collection/tests/outputs/StratfordUponAvonCouncil.json
  uk_bin_collection/uk_bin_collection/councils/StratfordUponAvonCouncil.py
Labels: python

#377 feat: Add support for Bury Council
  uk_bin_collection/tests/council_schemas/BuryCouncil.schema
  uk_bin_collection/tests/features/validate_council_outputs.feature
  uk_bin_collection/tests/input.json
  uk_bin_collection/tests/outputs/BuryCouncil.json
  uk_bin_collection/uk_bin_collection/councils/BuryCouncil.py
  wiki/Councils.md
Labels: python

#379 feat: Add support for EastSuffolkCouncil
  uk_bin_collection/tests/council_schemas/EastSuffolkCouncil.schema
  uk_bin_collection/tests/features/validate_council_outputs.feature
  uk_bin_collection/tests/input.json
  uk_bin_collection/tests/outputs/EastSuffolkCouncil.json
  uk_bin_collection/uk_bin_collection/councils/EastSuffolkCouncil.py
Labels: python

#384 Add support for multiple councils using similar systems
  uk_bin_collection/tests/council_schemas/EastLindseyDistrictCouncil.schema
  uk_bin_collection/tests/council_schemas/GatesheadCouncil.schema
  uk_bin_collection/tests/council_schemas/StaffordshireMoorlandsDistrictCouncil.schema
  uk_bin_collection/tests/council_schemas/WestLothianCouncil.schema
  uk_bin_collection/tests/features/validate_council_outputs.feature
  uk_bin_collection/tests/input.json
  uk_bin_collection/tests/outputs/EastLindseyDistrictCouncil.json
  uk_bin_collection/tests/outputs/GatesheadCouncil.json
  uk_bin_collection/tests/outputs/StaffordshireMoorlandsDistrictCouncil.json
  uk_bin_collection/tests/outputs/WestLothianCouncil.json
  uk_bin_collection/uk_bin_collection/councils/EastLindseyDistrictCouncil.py
  uk_bin_collection/uk_bin_collection/councils/GatesheadCouncil.py
  uk_bin_collection/uk_bin_collection/councils/StaffordshireMoorlandsDistrictCouncil.py
  uk_bin_collection/uk_bin_collection/councils/WestLothianCouncil.py
Labels: python

#392 fix: Fix input.json order
  uk_bin_collection/tests/input.json
Labels: bug

#396 fix: Fix Chelmsford City Council
  uk_bin_collection/tests/council_schemas/ChelmsfordCityCouncil.schema
  uk_bin_collection/tests/input.json
  uk_bin_collection/tests/outputs/ChelmsfordCityCouncil.json
  uk_bin_collection/uk_bin_collection/councils/ChelmsfordCityCouncil.py
Labels: bug, python

#397 fix: Home Assistant custom component fix for Selenium based councils
  poetry.lock
  pyproject.toml
  uk_bin_collection/uk_bin_collection/common.py
  uk_bin_collection/uk_bin_collection/councils/BroxtoweBoroughCouncil.py
  uk_bin_collection/uk_bin_collection/councils/BuckinghamshireCouncil.py
  uk_bin_collection/uk_bin_collection/councils/DerbyshireDalesDistrictCouncil.py
  uk_bin_collection/uk_bin_collection/councils/EastLindseyDistrictCouncil.py
  uk_bin_collection/uk_bin_collection/councils/EastSuffolkCouncil.py
  uk_bin_collection/uk_bin_collection/councils/GatesheadCouncil.py
  uk_bin_collection/uk_bin_collection/councils/HighPeakCouncil.py
  uk_bin_collection/uk_bin_collection/councils/NeathPortTalbotCouncil.py
  uk_bin_collection/uk_bin_collection/councils/NorthNorfolkDistrictCouncil.py
  uk_bin_collection/uk_bin_collection/councils/NorthumberlandCouncil.py
  uk_bin_collection/uk_bin_collection/councils/PrestonCityCouncil.py
  uk_bin_collection/uk_bin_collection/councils/ReigateAndBansteadBoroughCouncil.py
  uk_bin_collection/uk_bin_collection/councils/RushcliffeBoroughCouncil.py
  uk_bin_collection/uk_bin_collection/councils/StaffordshireMoorlandsDistrictCouncil.py
  uk_bin_collection/uk_bin_collection/councils/WakefieldCityCouncil.py
  uk_bin_collection/uk_bin_collection/councils/WestLothianCouncil.py
Labels: bug, python

#398 feat: Add support for Calderdale Council
  uk_bin_collection/tests/council_schemas/CalderdaleCouncil.schema
  uk_bin_collection/tests/features/validate_council_outputs.feature
  uk_bin_collection/tests/input.json
  uk_bin_collection/tests/outputs/CalderdaleCouncil.json
  uk_bin_collection/uk_bin_collection/councils/CalderdaleCouncil.py
Labels: python
